# SPDX-FileCopyrightText: 2021 Felipe Lema <felipelema@mortemale.org>
# SPDX-FileCopyrightText: 2022 Nicol√°s Alvarez <nicolas.alvarez@gmail.com>
# SPDX-License-Identifier: CC0-1.0

variables:
  DEBIAN_FRONTEND: "noninteractive"
  release_branch_pattern: '/^release\/.*/'

  DEPS_BRANCH_NAME_WINDOWS: 'master'
  DEPS_BRANCH_NAME_LINUX: 'master'
  DEPS_BRANCH_NAME_MACOS: 'master'
  DEPS_BRANCH_NAME_ANDROID: 'master'

  DEPS_REPO_BRANCH_NAME_WINDOWS: 'master'
  DEPS_REPO_BRANCH_NAME_LINUX: 'master'
  DEPS_REPO_BRANCH_NAME_MACOS: 'master'
  DEPS_REPO_BRANCH_NAME_ANDROID: 'master'

  VM_IMAGE_NAME_WINDOWS: 'storage.kde.org/vm-images/krita-windows-clang18-twinpy'
  VM_IMAGE_NAME_LINUX: 'storage.kde.org/vm-images/krita-appimage-2204'
  VM_IMAGE_NAME_ANDROID: 'storage.kde.org/vm-images/krita-android-sdk35-2204'

  # The name of python executable that will be used for initializing
  # the initial virtual envioronment. After venv is initialized, the chosen
  # python can be addressed via plain 'python' or 'python3'
  BOOTSTRAP_PYTHON_EXE_WINDOWS: 'C:\tools\Python-3.10\python.exe'

.nightly-job-mixin:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $KRITACI_SCHEDULED_JOB_NAME == "nightly"
      when: always

.weekly-job-mixin:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $KRITACI_SCHEDULED_JOB_NAME == "weekly"
      when: always

.ci-manual-job-mixin:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH =~ $release_branch_pattern
      when: never
    - when: manual

.ci-always-job-mixin:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH =~ $release_branch_pattern
      when: never
    - when: always

.ci-release-job-mixin:
  interruptible: false
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH =~ $release_branch_pattern
      when: manual

.ci-artifacts-with-packages-mixin:
  artifacts:
    name: krita-$CI_COMMIT_REF_SLUG-$CI_COMMIT_REF_NAME
    expire_in: 10 days
    when: always
    paths:
      - "**/failed_test_shot_*.png" # deprecated use appium_artifact_ instead
      - "**/appium_artifact_*"
      - "*.log"
      - "_build/CMakeFiles/CMakeConfigureLog.yaml"
      # Windows packages
      - "krita-*.zip"
      - "krita-*-setup.exe"
      - "krita-*.msix"
      # Linux, MacOS and Android packages
      - "_packaging"
      # Logs from MacOS signer/notarizer
      - "_dmg/*.log"
    reports:
      junit: JUnitTestResults.xml
      coverage_report:
        coverage_format: cobertura
        path: CoberturaLcovResults.xml

# nightly packages should not store the packages, since
# they are uploaded to CDN
.ci-artifacts-without-packages-mixin:
  artifacts:
    name: krita-$CI_COMMIT_REF_SLUG-$CI_COMMIT_REF_NAME-no-packages
    expire_in: 10 days
    when: always
    paths:
      - "**/failed_test_shot_*.png" # deprecated use appium_artifact_ instead
      - "**/appium_artifact_*"
      - "*.log"
      - "_packaging/*.log"
      # Logs from MacOS signer/notarizer
      - "_dmg/*.log"
    reports:
      junit: JUnitTestResults.xml
      coverage_report:
        coverage_format: cobertura
        path: CoberturaLcovResults.xml

workflow:
  rules:
    # Prevent branch pipelines if an MR is open on the branch.
    - if: $CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS && $CI_COMMIT_BRANCH !~ $release_branch_pattern
      when: never
    # Allow merge request pipelines.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # don't create pipelines for tags, since it is impossible to sign them
    - if: $CI_COMMIT_TAG
      when: never
    # Build branches too
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^krita\//
    - if: $CI_COMMIT_BRANCH =~ $release_branch_pattern

.clang_format:
  stage: build
  allow_failure: true
  image: invent-registry.kde.org/sysadmin/ci-images/suse-qt69:latest
  tags:
    - Linux
  before_script:
    - git clone https://invent.kde.org/sysadmin/ci-utilities.git --depth=1
  script:
    - git config --global --add safe.directory $CI_PROJECT_DIR
    - if [[ ! -f .clang-format && ! -f _clang-format ]]; then wget -O .clang-format https://invent.kde.org/frameworks/extra-cmake-modules/-/raw/master/kde-modules/clang-format.cmake; fi
    - ./ci-utilities/run-clang-format.py


include:
  - local: /build-tools/ci-scripts/linux.yml
  - local: /build-tools/ci-scripts/windows.yml
  - local: /build-tools/ci-scripts/android.yml
  - local: /build-tools/ci-scripts/macos.yml
  - project: sysadmin/ci-utilities
    file:
      - /gitlab-templates/cppcheck.yml
