# SPDX-FileCopyrightText: 2021 Felipe Lema <felipelema@mortemale.org>
# SPDX-FileCopyrightText: 2022 Nicol√°s Alvarez <nicolas.alvarez@gmail.com>
# SPDX-License-Identifier: CC0-1.0

variables:
  DEBIAN_FRONTEND: "noninteractive"

.nightly-job-mixin:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule" && $KRITACI_SCHEDULED_JOB_NAME == "nightly"
      when: always

.ci-manual-job-mixin:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: manual

.ci-always-job-mixin:
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: always

.ci-artifacts-with-packages-mixin:
  artifacts:
    name: krita-$CI_COMMIT_REF_SLUG-$CI_COMMIT_REF_NAME
    expire_in: 10 days
    when: always
    paths:
      - "**/failed_test_shot_*.png" # deprecated use appium_artifact_ instead
      - "**/appium_artifact_*"
      - "*.log"
      # Windows packages
      - "krita-*.zip"
      - "krita-*-setup.exe"
      - "krita-*.msix"
      # Linux, MacOS and Android packages
      - "_packaging"
    reports:
      junit: JUnitTestResults.xml
      coverage_report:
        coverage_format: cobertura
        path: CoberturaLcovResults.xml

# nightly packages should not store the packages, since
# they are uploaded to CDN
.ci-artifacts-without-packages-mixin:
  artifacts:
    name: krita-$CI_COMMIT_REF_SLUG-$CI_COMMIT_REF_NAME-no-packages
    expire_in: 10 days
    when: always
    paths:
      - "**/failed_test_shot_*.png" # deprecated use appium_artifact_ instead
      - "**/appium_artifact_*"
      - "*.log"
      - "_packaging/*.log"
    reports:
      junit: JUnitTestResults.xml
      coverage_report:
        coverage_format: cobertura
        path: CoberturaLcovResults.xml

clang_format:
  stage: build
  image: debian:testing
  before_script:
    - apt-get update
    - apt-get install --yes --no-install-recommends wget ca-certificates git clang-format-11
    - update-ca-certificates
  script:
    - ./.gitlab-ci.script
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - when: manual
      allow_failure: true

workflow:
  rules:
    # Prevent branch pipelines if an MR is open on the branch.
    - if: $CI_COMMIT_BRANCH && $CI_PIPELINE_SOURCE == "push" && $CI_OPEN_MERGE_REQUESTS
      when: never
    # Allow merge request pipelines.
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    # Build tags and branches too
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_COMMIT_BRANCH =~ /^krita\//

include:
  - local: /build-tools/ci-scripts/cppcheck.yml
  - local: /build-tools/ci-scripts/linux.yml
  - local: /build-tools/ci-scripts/windows.yml
  - local: /build-tools/ci-scripts/android.yml
  - local: /build-tools/ci-scripts/macos.yml
